---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Amys Portfolios"
keywords:    "A landing page for my different website"
description: "Check out all of my different blogs for games development, art and other!"
source_link: "https://github.com/AmyE123"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: 


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  babypurple: '#d0b8e9'
  babygreen: '#b9e9b9'
  darkgreen: '#184d18'
  babyblue: '#b9eaeb'
  darkblue: '#164e4f'
  babypink: '#eab9d1'
  darkpink: '#4e1732'

kramdown:
  auto_ids:  false

